# frozen_string_literal: true

# Gemfile

source 'http://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# Specify your gem's dependencies in juno.gemspec
gemspec
