version: "3"
services:
 otel-collector:
  container_name: "otel-collector"
  image: otel/opentelemetry-collector-contrib
  restart: always
  command: 
    - --config=/etc/otelcol-contrib/otel-config.yaml
  volumes:
    - ./otel-collector-config.yaml:/etc/otelcol-contrib/otel-config.yaml
  ports:
    - "1888:1888" # pprof extension
    - "8888:8888" # Prometheus metrics exposed by the Collector
    - "8889:8889" # Prometheus exporter metrics
    - "13133:13133" # health_check extension
    - "4317:4317" # OTLP gRPC receiver
    - "4318:4318" # OTLP http receiver
    - "55679:55679" # zpages extension
 
 prometheus:
  image: prom/prometheus
  container_name: prometheus
  restart: always
  command:
      - --config.file=/etc/prometheus/prometheus.yml
  ports:
      - "9090:9090"
  volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus

 grafana:
    container_name: grafana
    image: grafana/grafana
    volumes:
      - ./grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    ports:
      - "3000:3000"

volumes:
  prometheus-data:
