global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889'] # Otlp
  # uncomment to enable prometheus metrics
  #- job_name: 'prometheus'
  #  static_configs:
  #    - targets: ['localhost:9090'] # Prometheus itself
