version: "3"

x-services:
  &service_default
  init: true
  restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
  extra_hosts:
    - "etcd:172.20.0.2"
  networks:
    junonet:
  env_file:
    - .env

services:
  etcd:
    <<: *service_default
    image: ghcr.io/paypal/junodb/junoclusterserv:${VERSION}
    container_name: etcd
    environment:
      CLIENT_PORT: "2379"
      DATA_DIR: .
      PEER_NAMES: "p0"
      PEER_PORT: "2378"
      INITIAL_CLUSTER: "172.20.0.2"
    expose:
      - "2379"
    healthcheck:
      test: "export ETCDCTL_API=3 && ./etcdctl endpoint health --cluster --endpoints=etcd:2379"
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      junonet:
        ipv4_address: 172.20.0.2

  clustercfg:
    <<: *service_default
    image: ghcr.io/paypal/junodb/junoclustercfg:${VERSION}
    container_name: clustercfg
    command:
      [
        "./clustermgr",
        "--config",
        "/opt/juno/enabled_config.toml",
        "--cmd",
        "store",
        "--type",
        "cluster_info"
      ]
    environment:
      NUM_ZONES: "1"
      SS_HOSTS: '[["storageserv"]]'
    depends_on:
      etcd:
        condition: service_healthy
    healthcheck:
      test: "nc -vz etcd 2379"
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    # volumes:
    #   - ${PWD}/config/cluster/config.toml:/opt/juno/config.toml

  storageserv:
    <<: *service_default
    image: ghcr.io/paypal/junodb/junostorageserv:${VERSION}
    container_name: storageserv
    depends_on:
      clustercfg:
        condition: service_healthy
    healthcheck:
      test: "nc -vz 127.0.0.1 8089"
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    ports:
      - "${SS_ADMIN_PORT}:8089"
    volumes:
      - ${PWD}/config/storageserv/config.toml:/opt/juno/config/config.toml
      - ${PWD}/config/storageserv/data:/opt/juno/data

  proxy:
    <<: *service_default
    image: ghcr.io/paypal/junodb/junoserv:${VERSION}
    container_name: proxy
    ports:
      - "${PROXY_ADMIN_PORT}:8088"
      - "${PROXY_TCP_PORT}:8080"
      - "${PROXY_TLS_PORT}:5080"
    healthcheck:
      test: "nc -vz 127.0.0.1 5080"
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      - storageserv
    volumes:
      - ${PWD}/config/proxy/config.toml:/opt/juno/config/config.toml
      - ${PWD}/config/secrets:/opt/juno/bin/secrets

  junoclient:
    <<: *service_default
    image: ghcr.io/paypal/junodb/junoclient:${VERSION}
    container_name: junoclient
    depends_on:
      - proxy
    healthcheck:
      test: "nc -vz proxy 5080"
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    volumes:
      - ${PWD}/config/client/config.toml:/opt/juno/config.toml
      - ${PWD}/config/secrets:/opt/juno/secrets

  otel:
    <<: *service_default
    image: otel/opentelemetry-collector:latest
    container_name: otel
    command: ["--config=/etc/otel-collector/config.yaml"]
    depends_on:
      - proxy
    volumes:
      - ${PWD}/config/otel/config.yaml:/etc/otel-collector/config.yaml
    ports:
      - "1888:1888" # pprof extension
      - "8888:8888" # Prometheus metrics exposed by the Collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
      - "55679:55679" # zpages extension

  prometheus:
    <<: *service_default
    container_name: prometheus
    image: prom/prometheus:latest
    depends_on:
      - proxy
    volumes:
      - ${PWD}/config/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

networks:
  junonet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
