version: "3"

x-services: &service_default
    init: true
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    extra_hosts:
      - "etcd:172.20.0.2"
    networks:
      junonet:
    env_file:
      - .env

services:
  etcd: 
    <<: *service_default
    image: registry.hub.docker.com/juno/junoclusterserv:${VERSION}
    container_name: etcd
    environment:
      CLIENT_PORT: "2379"
      DATA_DIR: .
      PEER_NAMES: "p0"
      PEER_PORT: "2378"
      INITIAL_CLUSTER: "172.20.0.2"
    expose: 
    - "2379"
    healthcheck:
      test: "export ETCDCTL_API=3 && ./etcdctl endpoint health --cluster --endpoints=etcd:2379"
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      junonet:
        ipv4_address: 172.20.0.2


  clustercfg:
    <<: *service_default
    image: registry.hub.docker.com/juno/junoclustercfg:${VERSION}
    container_name: clustercfg
    command: ["./clustermgr", "--config", "/opt/juno/enabled_config.toml", "--cmd", "store", "--type", "cluster_info"]
    environment:
      NUM_ZONES: "1"
      SS_HOSTS: '[["storageserv"]]'
    depends_on:
      etcd:
        condition: service_healthy
    healthcheck:
      test: "nc -vz etcd 2379"
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    volumes:
    - ${PWD}/config/cluster/config.toml:/opt/juno/config.toml

  storageserv:
    <<: *service_default
    image: registry.hub.docker.com/juno/junostorageserv:${VERSION}
    container_name: storageserv
    depends_on:
      clustercfg:
        condition: service_healthy
    healthcheck:
      test: "nc -vz 127.0.0.1 8089"
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    ports:
    - "8089:8089"
    volumes:
    - ${PWD}/config/storageserv/config.toml:/opt/juno/config/config.toml

  proxy:
    <<: *service_default
    image: registry.hub.docker.com/juno/junoserv:${VERSION}
    container_name: proxy
    ports:
    - "8088:8088"
    - "8080:8080"
    - "5080:5080"
    healthcheck:
      test: "nc -vz 127.0.0.1 5080"
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    depends_on:
      - storageserv
    volumes:
    - ${PWD}/config/proxy/config.toml:/opt/juno/config/config.toml
    - ${PWD}/config/secrets:/opt/juno/bin/secrets

networks:
  junonet:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.0.0/16


