name: Client FT

on:
  push:
    branches:
      - main
      - test
      - dev
    paths-ignore:
      - ".github/workflows/**"
  pull_request:
    branches:
      - main
    paths-ignore:
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  build-juno-docker:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Build with Maven
        run: mvn -B -U install --file client/Java/Juno/pom.xml
      - name: Run functional tests
        run: mvn -B -U install --file client/Java/Juno/FunctionalTests/pom.xml