name: Binary Build

on:
  push:
    branches:
      - main
      - dev*
      - dev**
    paths-ignore:
      - ".github/workflows/*"
  pull_request:
    types:
      - opened
    branches:
      - main
    paths-ignore:
      - ".github/workflows/*"
  workflow_dispatch:

jobs:
  build-juno-binaries:
    strategy:
      matrix:
        os: [ubuntu-latest]
        go_version: ["^1.18.2"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install golang
        uses: actions/setup-go@v3
        with:
          go-version: "${{ matrix.go_version }}"
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install build-essential -y
          sudo apt-get install libgflags-dev libsnappy-dev zlib1g-dev libbz2-dev liblz4-dev libzstd-dev -y
          sudo apt install openssl -y
          echo "Dependencies version"
          echo "GCC Version:" `gcc --version`
          echo "G++ Version:" `g++ --version`
          echo "Openssl Version:" `openssl version`
      - name: Build binaries
        id: run-build
        run: |
          export BUILDTOP=`pwd`
          binary_build/build.sh
